### ISSUE TITLE
Не отправляет часть сообщений

### ISSUE THREAD

**Issue by vladimirkhs** [maxemontio/promegram#2]
Ошибка в консоли:
```
Unhandled rejection Error: ETELEGRAM: 400 Bad Request: can't parse entities: Unsupported start tag "" at byte offset 152
    at /promegram/node_modules/node-telegram-bot-api/src/telegram.js:284:15
    at tryCatcher (/promegram/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/promegram/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/promegram/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/promegram/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/promegram/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/promegram/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/promegram/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/promegram/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/promegram/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
Unhandled rejection Error: ETELEGRAM: 400 Bad Request: can't parse entities: Unsupported start tag "" at byte offset 153
    at /promegram/node_modules/node-telegram-bot-api/src/telegram.js:284:15
    at tryCatcher (/promegram/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/promegram/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/promegram/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/promegram/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/promegram/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/promegram/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/promegram/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/promegram/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/promegram/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
```
Алерт:

`{"id":"2291471504024460441","name":"NodeCriticalOutOfMemory","group_id":"7882461115807351686","expression":"node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 \u003c 10","state":"firing","value":"8.587514058326434e+00","labels":{"alertgroup":"resources-memory","group":"Linux servers|Hosts / GROUP / Prod","hostid":"10362","hostname":"vm001","instance":"192.168.0.1:9182","job":"node-exporter-scrape","monitor":"host-monitoring","severity":"critical","visiblename":"vm001"},"annotations":{"description":"Дополнительная информация: \n Метки маршрутизации оповещения: critical | host-monitoring","summary":"Host out of memory (instance vm001) \n\n description: Node memory is filling up (\u003c 10% left) \n  VALUE = 8.587514058326434 \n  LABELS: map[alertgroup:resources-memory group:Linux servers|Hosts / GROUP / Prod hostid:10362 hostname:vm001 instance:192.168.0.1:9182 job:node-exporter-scrape monitor:host-monitoring severity:critical visiblename:vm001]"},"activeAt":"2021-03-29T16:57:10.280611883Z"}`

**Comment by maxemontio** [comment]
@vladimirkhs проблема в поле `summary`, а именно в `(\u003c 10% left)`. \u воспринимается как управляющий символ, отсюда проблема. Если экранировать слеш, или вообще заменить набор этих символов - алерт улетает корректно.

**Comment by vladimirkhs** [comment]
Спасибо! Работает!
